In [1]:
%load_ext autoreload
%autoreload 2

import itertools
import pickle

import numpy as np
import pandas as pd
import pycuber as pc

from classes.cube_classes import Cube3State, Cube3
from generate.generate_states import generate_symmetric_cubes, ids_to_color, states_to_color
from generate.generate_random_states import generate_random_states_and_generators
from generate.symmetry_config import actions

from utils.plot_compression import plot_histo

In [8]:
cube = Cube3()
goal_state = cube.generate_goal_states(1)[0]
prev_states = [cube.prev_state([goal_state], i)[0] for i in range(12)]
print(prev_states[0].colors.shape, '\n')

for state in prev_states:
    for s in range(6):
        for i in range(3):
            print(state.colors[s*9 + i*3: s*9 + (i+1)*3])
    print('')

(54,) 

[6 3 0]
[7 4 1]
[8 5 2]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 47]
[21 22 50]
[24 25 53]
[27 28 38]
[30 31 41]
[33 34 44]
[36 37 20]
[39 40 23]
[42 43 26]
[45 46 29]
[48 49 32]
[51 52 35]

[2 5 8]
[1 4 7]
[0 3 6]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 38]
[21 22 41]
[24 25 44]
[27 28 47]
[30 31 50]
[33 34 53]
[36 37 29]
[39 40 32]
[42 43 35]
[45 46 20]
[48 49 23]
[51 52 26]

[0 1 2]
[3 4 5]
[6 7 8]
[15 12  9]
[16 13 10]
[17 14 11]
[36 19 20]
[39 22 23]
[42 25 26]
[45 28 29]
[48 31 32]
[51 34 35]
[27 37 38]
[30 40 41]
[33 43 44]
[18 46 47]
[21 49 50]
[24 52 53]

[0 1 2]
[3 4 5]
[6 7 8]
[11 14 17]
[10 13 16]
[ 9 12 15]
[45 19 20]
[48 22 23]
[51 25 26]
[36 28 29]
[39 31 32]
[42 34 35]
[18 37 38]
[21 40 41]
[24 43 44]
[27 46 47]
[30 49 50]
[33 52 53]

[44 43 42]
[3 4 5]
[6 7 8]
[45 46 47]
[12 13 14]
[15 16 17]
[24 21 18]
[25 22 19]
[26 23 20]
[27 28 29]
[30 31 32]
[33 34 35]
[36 37 38]
[39 40 41]
[11 10  9]
[0 1 2]
[48 49 50]
[51 52 53]

[45 46 47]
[3 4 5]
[6 7 8]
[44 43 42]
[12 

In [9]:
cube.rotate_idxs_new

{'U-1': array([ 0,  1,  2,  2,  5,  8,  8,  7,  6,  6,  3,  0, 20, 23, 26, 47, 50,
        53, 29, 32, 35, 38, 41, 44], dtype=int64),
 'U1': array([ 0,  1,  2,  2,  5,  8,  8,  7,  6,  6,  3,  0, 20, 23, 26, 47, 50,
        53, 29, 32, 35, 38, 41, 44], dtype=int64),
 'D-1': array([ 9, 10, 11, 11, 14, 17, 17, 16, 15, 15, 12,  9, 18, 21, 24, 36, 39,
        42, 27, 30, 33, 45, 48, 51], dtype=int64),
 'D1': array([ 9, 10, 11, 11, 14, 17, 17, 16, 15, 15, 12,  9, 18, 21, 24, 36, 39,
        42, 27, 30, 33, 45, 48, 51], dtype=int64),
 'L-1': array([18, 19, 20, 20, 23, 26, 26, 25, 24, 24, 21, 18,  0,  1,  2, 44, 43,
        42,  9, 10, 11, 45, 46, 47], dtype=int64),
 'L1': array([18, 19, 20, 20, 23, 26, 26, 25, 24, 24, 21, 18,  0,  1,  2, 44, 43,
        42,  9, 10, 11, 45, 46, 47], dtype=int64),
 'R-1': array([27, 28, 29, 29, 32, 35, 35, 34, 33, 33, 30, 27,  6,  7,  8, 51, 52,
        53, 15, 16, 17, 38, 37, 36], dtype=int64),
 'R1': array([27, 28, 29, 29, 32, 35, 35, 34, 33, 33, 30, 27,  6,